export const signup = async(req,res)=>{
    try {
        
        
    } catch (error) {
        console.log("error in signup",error)
    }
}

export const login = async(req,res)=>{
    try {
        
        
    } catch (error) {
        console.log("error in login",error)
    }
}
export const logout = async(req,res)=>{
    try {
        
        
    } catch (error) {
        console.log("error in logout",error)
    }
}